apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-service
  namespace : {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  # type: 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  clusterIP: None
